import {
  User,
  UserRole,
  MiningZone,
  Vehicle,
  Sensor,
  Alert,
  Incident,
  ManagementOverviewData,
  Organization
} from '../types';
import { MiningSite } from '../types';

export const MOCK_SITES: MiningSite[] = [
  {
    id: 'site-kirandul-01',
    organizationId: 'org-nmdc-01',
    name: 'Kirandul Iron Ore Complex',
    code: 'NMDC-KRD-14',
    location: 'Bailadila Deposit 14, Dantewada',
    state: 'Chhattisgarh',
    coordinates: [18.6312, 81.2485],
    status: 'CRITICAL',
    currentCondition: {
      visibilityMeters: 3.2,
      fogLevelPercent: 78,
      humidityPercent: 88,
      temperatureCelsius: 22,
      status: 'DENSE_FOG',
      updatedAt: new Date().toISOString(),
    },
    totalVehicles: 82,
    totalSensors: 436,
    activeAlertsCount: 7,
  },
  {
    id: 'site-bacheli-02',
    organizationId: 'org-nmdc-01',
    name: 'Bacheli Complex Mine',
    code: 'NMDC-BCH-05',
    location: 'Bailadila Deposit 5, Bacheli',
    state: 'Chhattisgarh',
    coordinates: [18.7124, 81.2842],
    status: 'OPERATIONAL',
    currentCondition: {
      visibilityMeters: 18.5,
      fogLevelPercent: 15,
      humidityPercent: 48,
      temperatureCelsius: 27,
      status: 'CLEAR',
      updatedAt: new Date().toISOString(),
    },
    totalVehicles: 64,
    totalSensors: 320,
    activeAlertsCount: 2,
  },
  {
    id: 'site-donimalai-03',
    organizationId: 'org-nmdc-01',
    name: 'Donimalai Iron Ore Mine',
    code: 'NMDC-DNM-02',
    location: 'Sandur, Bellary District',
    state: 'Karnataka',
    coordinates: [15.0562, 76.6125],
    status: 'OPERATIONAL',
    currentCondition: {
      visibilityMeters: 14.0,
      fogLevelPercent: 20,
      humidityPercent: 52,
      temperatureCelsius: 29,
      status: 'CLEAR',
      updatedAt: new Date().toISOString(),
    },
    totalVehicles: 48,
    totalSensors: 210,
    activeAlertsCount: 1,
  },
  {
    id: 'site-bailadila-04',
    organizationId: 'org-nmdc-01',
    name: 'Bailadila Deposit 11B Mine',
    code: 'NMDC-BLD-11',
    location: 'South Bastar, Dantewada',
    state: 'Chhattisgarh',
    coordinates: [18.6750, 81.2380],
    status: 'WARNING',
    currentCondition: {
      visibilityMeters: 6.5,
      fogLevelPercent: 54,
      humidityPercent: 76,
      temperatureCelsius: 24,
      status: 'MODERATE_FOG',
      updatedAt: new Date().toISOString(),
    },
    totalVehicles: 76,
    totalSensors: 388,
    activeAlertsCount: 4,
  },
];

export const MOCK_USERS: Record<UserRole, User> = {
  SUPER_ADMIN: {
    id: 'usr-super-01',
    email: 'admin.platform@minesafe.gov.in',
    displayName: 'Vikramaditya Sharma',
    photoURL: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150',
    role: 'SUPER_ADMIN',
    organizationId: 'org-platform-00',
    organizationName: 'Ministry of Mines & Central Intelligence',
    assignedSiteIds: MOCK_SITES.map(s => s.id),
    permissions: ['*'],
  },
  SITE_ADMIN: {
    id: 'usr-site-01',
    email: 'site.admin@nmdc.co.in',
    displayName: 'Rajesh Kumar Verma',
    photoURL: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150',
    role: 'SITE_ADMIN',
    organizationId: 'org-nmdc-01',
    organizationName: 'NMDC Limited',
    assignedSiteIds: ['site-kirandul-01', 'site-bacheli-02', 'site-donimalai-03', 'site-bailadila-04'],
    permissions: ['site:manage', 'vehicles:manage', 'sensors:manage', 'alerts:manage'],
  },
  CONTROL_ROOM_OPERATOR: {
    id: 'usr-control-01',
    email: 'control.room@kirandul.nmdc.co.in',
    displayName: 'Priya Sundaram',
    photoURL: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=150',
    role: 'CONTROL_ROOM_OPERATOR',
    organizationId: 'org-nmdc-01',
    organizationName: 'NMDC Kirandul Operations',
    assignedSiteIds: ['site-kirandul-01'],
    permissions: ['control:monitor', 'alerts:acknowledge', 'alerts:escalate', 'zones:restrict'],
  },
  VEHICLE_OPERATOR: {
    id: 'usr-driver-104',
    email: 'operator.d104@kirandul.nmdc.co.in',
    displayName: 'Suresh Patel (Operator D-104)',
    photoURL: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150',
    role: 'VEHICLE_OPERATOR',
    organizationId: 'org-nmdc-01',
    organizationName: 'Kirandul Mining Fleet',
    assignedSiteIds: ['site-kirandul-01'],
    assignedVehicleId: 'veh-d104',
    permissions: ['vehicle:read', 'alerts:ack_driver'],
  },
  MANAGEMENT: {
    id: 'usr-mgmt-01',
    email: 'gm.operations@nmdc.co.in',
    displayName: 'Dr. Ananya Roy',
    photoURL: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=150',
    role: 'MANAGEMENT',
    organizationId: 'org-nmdc-01',
    organizationName: 'NMDC Executive Board',
    assignedSiteIds: MOCK_SITES.map(s => s.id),
    permissions: ['analytics:view', 'reports:export', 'management:overview'],
  },
};

export const MOCK_ORGANIZATIONS: Organization[] = [
  {
    id: 'org-nmdc-01',
    name: 'NMDC Limited (National Mineral Dev Corp)',
    code: 'NMDC',
    region: 'Central India Hub',
    totalSites: 4,
    totalVehicles: 74,
    status: 'ACTIVE',
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'org-secl-01',
    name: 'South Eastern Coalfields Limited',
    code: 'SECL',
    region: 'Chhattisgarh Coal Belt',
    totalSites: 6,
    totalVehicles: 120,
    status: 'ACTIVE',
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: 'org-tata-01',
    name: 'Tata Steel Mining Division',
    code: 'TSL-MINE',
    region: 'Odisha & Jharkhand Ore Belt',
    totalSites: 5,
    totalVehicles: 90,
    status: 'ACTIVE',
    createdAt: '2024-03-10T00:00:00Z',
  },
];

export const MOCK_ZONES: MiningZone[] = [
  {
    id: 'zone-b4',
    siteId: 'site-kirandul-01',
    name: 'Pit Bench B-4 (Active Excavation)',
    code: 'PIT-B4',
    polygonCoordinates: [
      [18.6330, 81.2460],
      [18.6345, 81.2490],
      [18.6320, 81.2510],
      [18.6305, 81.2475],
    ],
    riskLevel: 'HIGH',
    maxSpeedLimit: 15,
    isRestricted: false,
    activeVehiclesCount: 4,
    description: 'Deep pit slope with reduced visibility during early morning fog.',
  },
  {
    id: 'zone-haul-ramp',
    siteId: 'site-kirandul-01',
    name: 'Main Haul Ramp #2 (Gradient 8%)',
    code: 'RAMP-H2',
    polygonCoordinates: [
      [18.6310, 81.2440],
      [18.6325, 81.2465],
      [18.6295, 81.2480],
      [18.6280, 81.2455],
    ],
    riskLevel: 'MEDIUM',
    maxSpeedLimit: 20,
    isRestricted: false,
    activeVehiclesCount: 5,
    description: 'High volume dumper ramp connecting pit floor to primary crusher.',
  },
  {
    id: 'zone-crusher',
    siteId: 'site-kirandul-01',
    name: 'Primary Crusher Hopper Zone',
    code: 'CRSH-01',
    polygonCoordinates: [
      [18.6275, 81.2500],
      [18.6290, 81.2520],
      [18.6270, 81.2535],
      [18.6255, 81.2515],
    ],
    riskLevel: 'SAFE',
    maxSpeedLimit: 10,
    isRestricted: false,
    activeVehiclesCount: 3,
    description: 'Tipping platform for 100-ton dumpers into jaw crusher hopper.',
  },
  {
    id: 'zone-blast-area',
    siteId: 'site-kirandul-01',
    name: 'Bench A-2 (Blasting Buffer Zone)',
    code: 'BLAST-A2',
    polygonCoordinates: [
      [18.6350, 81.2500],
      [18.6370, 81.2530],
      [18.6340, 81.2550],
      [18.6320, 81.2520],
    ],
    riskLevel: 'EXTREME',
    maxSpeedLimit: 0,
    isRestricted: true,
    activeVehiclesCount: 0,
    description: 'Restricted area due to active explosive loading operations.',
  },
];

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: 'veh-d104',
    siteId: 'site-kirandul-01',
    zoneId: 'zone-b4',
    code: 'D-104',
    name: 'CAT 777G Haul Dumper (100T)',
    type: 'DUMPER',
    operatorId: 'usr-driver-104',
    operatorName: 'Suresh Patel',
    operatorPhone: '+91 98765 43210',
    status: 'CRITICAL',
    telemetry: {
      speedKmh: 18,
      recommendedSpeedKmh: 10,
      latitude: 18.6325,
      longitude: 81.2482,
      heading: 135,
      fuelLevelPercent: 78,
      engineTempCelsius: 88,
      nearestVehicleId: 'veh-d108',
      nearestVehicleName: 'D-108 (Komatsu HD785)',
      nearestVehicleDistanceMeters: 3.2,
      relativeSpeedKmh: +14,
      riskScorePercent: 91,
      riskLevel: 'CRITICAL',
      riskFactors: [
        'Dense Fog (Visibility < 3.5m)',
        'Blind Curve Approaching',
        'Head-on Collision Trajectory with D-108',
        'Speed Exceeds Safe Braking Distance'
      ],
      recommendedAction: 'REDUCE SPEED TO 8 KM/H IMMEDIATELY & ENGAGE AUXILIARY BRAKE',
      lastUpdate: new Date().toISOString(),
    },
    sensorsAttached: ['sns-rad-104', 'sns-lid-104', 'sns-gps-104'],
  },
  {
    id: 'veh-d108',
    siteId: 'site-kirandul-01',
    zoneId: 'zone-b4',
    code: 'D-108',
    name: 'Komatsu HD785 Dumper',
    type: 'DUMPER',
    operatorId: 'usr-driver-108',
    operatorName: 'Ramesh Naidu',
    operatorPhone: '+91 98765 43211',
    status: 'HIGH_RISK',
    telemetry: {
      speedKmh: 14,
      recommendedSpeedKmh: 10,
      latitude: 18.6323,
      longitude: 81.2485,
      heading: 315,
      fuelLevelPercent: 62,
      engineTempCelsius: 84,
      nearestVehicleId: 'veh-d104',
      nearestVehicleName: 'D-104 (CAT 777G)',
      nearestVehicleDistanceMeters: 3.2,
      relativeSpeedKmh: -14,
      riskScorePercent: 82,
      riskLevel: 'HIGH_RISK',
      riskFactors: [
        'Approaching D-104 in Narrow Cutting',
        'Low Light Condition'
      ],
      recommendedAction: 'HOLD POSITION / SHIFT TO LEFT RAMP SHOULDER',
      lastUpdate: new Date().toISOString(),
    },
    sensorsAttached: ['sns-rad-108', 'sns-gps-108'],
  },
  {
    id: 'veh-ex201',
    siteId: 'site-kirandul-01',
    zoneId: 'zone-b4',
    code: 'EX-201',
    name: 'Hitachi EX1200 Hydraulic Shovel',
    type: 'EXCAVATOR',
    operatorId: 'usr-driver-ex201',
    operatorName: 'Mahesh Swamy',
    status: 'SAFE',
    telemetry: {
      speedKmh: 0,
      recommendedSpeedKmh: 0,
      latitude: 18.6338,
      longitude: 81.2470,
      heading: 45,
      fuelLevelPercent: 89,
      engineTempCelsius: 75,
      riskScorePercent: 12,
      riskLevel: 'SAFE',
      riskFactors: [],
      recommendedAction: 'NORMAL EXCAVATION OPERATIONAL',
      lastUpdate: new Date().toISOString(),
    },
    sensorsAttached: ['sns-lid-ex201', 'sns-gps-ex201'],
  },
  {
    id: 'veh-p301',
    siteId: 'site-kirandul-01',
    zoneId: 'zone-haul-ramp',
    code: 'P-301',
    name: 'Mahindra Scorpio Safety Patrol',
    type: 'PATROL',
    operatorId: 'usr-driver-p301',
    operatorName: 'Safety Inspector Das',
    status: 'WARNING',
    telemetry: {
      speedKmh: 28,
      recommendedSpeedKmh: 20,
      latitude: 18.6300,
      longitude: 81.2450,
      heading: 210,
      fuelLevelPercent: 95,
      engineTempCelsius: 82,
      nearestVehicleId: 'veh-d102',
      nearestVehicleDistanceMeters: 24,
      riskScorePercent: 48,
      riskLevel: 'WARNING',
      riskFactors: ['Exceeding Zone Speed Limit (28 km/h vs 20 km/h)'],
      recommendedAction: 'REDUCE SPEED ON GRADIENT RAMP',
      lastUpdate: new Date().toISOString(),
    },
    sensorsAttached: ['sns-gps-p301'],
  },
];

export const MOCK_SENSORS: Sensor[] = [
  {
    id: 'sns-rad-104',
    siteId: 'site-kirandul-01',
    vehicleId: 'veh-d104',
    vehicleCode: 'D-104',
    zoneId: 'zone-b4',
    name: 'Front mmWave Radar 77GHz',
    type: 'RADAR',
    status: 'ONLINE',
    health: {
      signalStrengthDbm: -58,
      batteryPercent: 98,
      isCalibrated: true,
      firmwareVersion: 'v3.4.12-pro',
    },
    directionAngle: 0, // Front
    detectionRangeMeters: 80,
    purpose: 'Measures front obstacle distance and relative closing velocity in dust/fog.',
    lastUpdate: new Date().toISOString(),
    telemetry: {
      radar: {
        distanceMeters: 3.2,
        relativeSpeedKmh: 28,
        objectsDetectedCount: 2,
        detectionAngleDegrees: 15,
        detectionRangeMeters: 80,
      },
    },
  },
  {
    id: 'sns-lid-104',
    siteId: 'site-kirandul-01',
    vehicleId: 'veh-d104',
    vehicleCode: 'D-104',
    zoneId: 'zone-b4',
    name: '3D LiDAR 32-Beam Scanner',
    type: 'LIDAR',
    status: 'DEGRADED',
    health: {
      signalStrengthDbm: -72,
      batteryPercent: 85,
      pointCloudHealthPercent: 64, // degraded by heavy fog
      isCalibrated: true,
      firmwareVersion: 'v2.1.0',
    },
    directionAngle: 0,
    detectionRangeMeters: 120,
    purpose: '3D point-cloud spatial mapping and blind-spot obstacle profile rendering.',
    lastUpdate: new Date().toISOString(),
    telemetry: {
      lidar: {
        objectsDetectedCount: 4,
        scanRangeMeters: 120,
        nearestObjectDistanceMeters: 3.2,
        pointCloudHealthPercent: 64,
        directionAngleDegrees: 0,
      },
    },
  },
  {
    id: 'sns-vis-station-01',
    siteId: 'site-kirandul-01',
    zoneId: 'zone-b4',
    name: 'Pit Bench B-4 Fog & Optical Transmissometer',
    type: 'VISIBILITY',
    status: 'ONLINE',
    health: {
      signalStrengthDbm: -52,
      batteryPercent: 100,
      isCalibrated: true,
      firmwareVersion: 'v4.0.1',
    },
    directionAngle: 180,
    detectionRangeMeters: 500,
    purpose: 'Monitors ambient meteorological atmospheric optical extinction and fog density.',
    lastUpdate: new Date().toISOString(),
    telemetry: {
      visibility: {
        visibilityMeters: 3.2,
        fogLevelPercent: 78,
        humidityPercent: 88,
        status: 'DENSE_FOG',
      },
    },
  },
  {
    id: 'sns-gps-104',
    siteId: 'site-kirandul-01',
    vehicleId: 'veh-d104',
    vehicleCode: 'D-104',
    zoneId: 'zone-b4',
    name: 'High-Precision RTK-DGPS Unit',
    type: 'GPS',
    status: 'ONLINE',
    health: {
      signalStrengthDbm: -48,
      batteryPercent: 94,
      isCalibrated: true,
      firmwareVersion: 'v5.8.9',
    },
    directionAngle: 0,
    detectionRangeMeters: 1000,
    purpose: 'Centimeter-level satellite positioning and vector heading calculation.',
    lastUpdate: new Date().toISOString(),
    telemetry: {
      gps: {
        latitude: 18.6325,
        longitude: 81.2482,
        speedKmh: 18,
        headingDegrees: 135,
        accuracyMeters: 0.08,
        satellitesConnected: 16,
      },
    },
  },
  {
    id: 'sns-gas-pit-01',
    siteId: 'site-kirandul-01',
    zoneId: 'zone-blast-area',
    name: 'Multi-Gas Pit Safety Sensor (CH4/CO/O2)',
    type: 'GAS',
    status: 'ONLINE',
    health: {
      signalStrengthDbm: -61,
      batteryPercent: 91,
      isCalibrated: true,
      firmwareVersion: 'v1.9.0',
    },
    directionAngle: 0,
    detectionRangeMeters: 50,
    purpose: 'Detects hazardous gas build-up (Methane, Carbon Monoxide) in deep pit benches.',
    lastUpdate: new Date().toISOString(),
    telemetry: {
      gas: {
        ch4Ppm: 120,
        coPpm: 8,
        o2Percent: 20.8,
        status: 'SAFE',
      },
    },
  },
];

export const MOCK_ALERTS: Alert[] = [
  {
    id: 'alt-col-9102',
    siteId: 'site-kirandul-01',
    category: 'COLLISION_RISK',
    severity: 'CRITICAL',
    status: 'ACTIVE',
    title: 'Predicted High-Speed Head-on Collision Risk',
    description: 'ML model predicts 91% collision probability between D-104 and D-108 near blind haul curve in Pit Bench B-4.',
    vehicleId: 'veh-d104',
    vehicleCode: 'D-104',
    secondaryVehicleId: 'veh-d108',
    secondaryVehicleCode: 'D-108',
    sensorId: 'sns-rad-104',
    sensorName: 'Front mmWave Radar 77GHz',
    zoneId: 'zone-b4',
    zoneName: 'Pit Bench B-4',
    currentValue: 'Distance: 3.2m | Closing Speed: +28 km/h | Vis: 3.2m',
    riskScorePercent: 91,
    recommendedAction: 'Reduce speed to 8 km/h & divert D-104 to outer safety turnout bench.',
    timestamp: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
  },
  {
    id: 'alt-vis-4401',
    siteId: 'site-kirandul-01',
    category: 'VISIBILITY_HAZARD',
    severity: 'HIGH',
    status: 'ACTIVE',
    title: 'Critical Fog Visibility Drop (< 4m)',
    description: 'Optical transmissometer detected fog density escalation in lower pit levels. Driving condition hazardous.',
    sensorId: 'sns-vis-station-01',
    sensorName: 'Pit Bench B-4 Fog Sensor',
    zoneId: 'zone-b4',
    zoneName: 'Pit Bench B-4',
    currentValue: 'Visibility: 3.2m (Threshold: 15m)',
    riskScorePercent: 76,
    recommendedAction: 'Enforce mandatory 10 km/h speed governor & turn on strobe fog lamps.',
    timestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
  {
    id: 'alt-spd-1002',
    siteId: 'site-kirandul-01',
    category: 'OVERSPEED',
    severity: 'WARNING',
    status: 'ACKNOWLEDGED',
    title: 'Ramp Speed Violation',
    description: 'Vehicle P-301 detected travelling at 28 km/h in 20 km/h max speed haul ramp zone.',
    vehicleId: 'veh-p301',
    vehicleCode: 'P-301',
    zoneId: 'zone-haul-ramp',
    zoneName: 'Main Haul Ramp #2',
    currentValue: 'Speed: 28 km/h (Limit: 20 km/h)',
    riskScorePercent: 48,
    recommendedAction: 'Alert driver to reduce speed on gradient slope.',
    timestamp: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    acknowledgedBy: 'Priya Sundaram (Control Room)',
    acknowledgedAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
  },
];

export const MOCK_INCIDENTS: Incident[] = [
  {
    id: 'inc-2026-041',
    siteId: 'site-kirandul-01',
    incidentNumber: 'INC-2026-041',
    title: 'Near-Miss Collision under Fog (Pit Bench B-4)',
    severity: 'HIGH',
    status: 'INVESTIGATING',
    vehicleIds: ['veh-d104', 'veh-d108'],
    vehicleCodes: ['D-104', 'D-108'],
    zoneId: 'zone-b4',
    zoneName: 'Pit Bench B-4',
    riskScore: 91,
    description: 'Radar & V2V early collision alert triggered auto-braking advisory. Vehicles passed within 3.2m in heavy fog.',
    rootCause: 'Reduced visibility combined with non-compliance with ramp speed limit during fog alert.',
    preventativeAction: 'Install automated speed governor triggered by atmospheric fog sensors.',
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: 'inc-2026-039',
    siteId: 'site-kirandul-01',
    incidentNumber: 'INC-2026-039',
    title: 'Radar Sensor Point-Cloud Degradation',
    severity: 'WARNING',
    status: 'RESOLVED',
    vehicleIds: ['veh-d102'],
    vehicleCodes: ['D-102'],
    zoneId: 'zone-crusher',
    zoneName: 'Primary Crusher Hopper Zone',
    riskScore: 42,
    description: 'Heavy mud accumulation on front 77GHz radar lens caused temporary signal attenuation.',
    rootCause: 'High moisture slurry at tipping bay.',
    preventativeAction: 'Re-calibrated and cleaned radar enclosure nozzle.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
  },
];

export const MOCK_MANAGEMENT_ANALYTICS: ManagementOverviewData = {
  safetyScore: 92,
  nearMissesCount: 4,
  criticalEventsCount: 1,
  activeVehiclesCount: 74,
  fleetUtilizationPercent: 86.4,
  avgCycleTimeMinutes: 24.5,
  idleTimePercent: 8.2,
  environmentalDowntimeHours: 3.5,
  highRiskZones: [
    { zoneName: 'Pit Bench B-4', riskScore: 78, incidentCount: 3 },
    { zoneName: 'Main Haul Ramp #2', riskScore: 54, incidentCount: 1 },
    { zoneName: 'Primary Crusher Bay', riskScore: 32, incidentCount: 0 },
  ],
  timeSeries: [
    { time: '06:00', safetyScore: 98, nearMisses: 0, criticalAlerts: 0, avgSpeedKmh: 24, visibilityMeters: 25, fleetUtilizationPercent: 90 },
    { time: '07:00', safetyScore: 96, nearMisses: 0, criticalAlerts: 0, avgSpeedKmh: 22, visibilityMeters: 18, fleetUtilizationPercent: 92 },
    { time: '08:00', safetyScore: 89, nearMisses: 1, criticalAlerts: 0, avgSpeedKmh: 19, visibilityMeters: 10, fleetUtilizationPercent: 88 },
    { time: '09:00', safetyScore: 78, nearMisses: 2, criticalAlerts: 1, avgSpeedKmh: 14, visibilityMeters: 4, fleetUtilizationPercent: 75 },
    { time: '10:00', safetyScore: 85, nearMisses: 1, criticalAlerts: 0, avgSpeedKmh: 16, visibilityMeters: 8, fleetUtilizationPercent: 82 },
    { time: '11:00', safetyScore: 92, nearMisses: 0, criticalAlerts: 0, avgSpeedKmh: 21, visibilityMeters: 16, fleetUtilizationPercent: 86 },
    { time: '12:00', safetyScore: 94, nearMisses: 0, criticalAlerts: 0, avgSpeedKmh: 23, visibilityMeters: 22, fleetUtilizationPercent: 89 },
  ],
};
